wandb:
  entity: "992262955-east-china-normal-university"
#  project: "test"
  tags: ["stereo", "monster"]
  notes: "monster cvpr 2025"

project_name: "test"
restore_ckpt: "./sceneflow.pth"
# restore_ckpt: "/data2/cjd/mono_fusion/checkpoints/sceneflow.pth"
logdir: './checkpoints/kitti/'
encoder: 'vitl'
batch_size: 1
train_datasets: ['kitti']
lr: 1e-4
wdecay: 1e-5
total_step: 50000
save_frequency: 2000
save_path: ./checkpoints/kitti/
val_frequency: 2000
image_size: [320, 736]
train_iters: 22
valid_iters: 32
val_dataset: 'kitti'
corr_implementation: "reg"
corr_levels: 2
corr_radius: 4
n_downsample: 2
n_gru_layers: 3
hidden_dims: [128, 128, 128]
max_disp: 192
saturation_range: [0.7, 1.3]
do_flip: False
spatial_scale: [-0.2, 0.5]
noyjitter: True
num_gpu: 1
seed: 655
